spring:
  profiles:
    active: development
  application:
    name: app
  jpa:
    open-in-view: false
rsa:
  private-key: classpath:private.pem
  public-key: classpath:public.pem
logging:
  level:
    org.springframework.security: TRACE